sudo: false
language: php
php:
  - 5.5
cache:
  directories:
    - $HOME/.composer/cache
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install  --prefer-dist --no-interaction
script:
  - phpunit --coverage-text tests
  - vendor/bin/phpcs --standard=phpcs.xml src
