sudo: false
language: php
php:
  - 5.3
  - 5.4
before_script:
  - pear channel-discover public.intraface.dk
  - pear install --force pear/File_CSV
  - pear install --force intrafacepublic/Ilib_ClassLoader
  - pear install --force intrafacepublic/File_EmptyFirstFieldBugFix
  - pear install --force intrafacepublic/Ilib_Error
  - phpenv rehash
script: phpunit --coverage-text tests
